### ISSUE TITLE
Extension affects another extension

### ISSUE THREAD

**Issue by stansult-h** [ayman/PrettyJSON#11]
When I have your extension on, the text inside another extension (Honey in this example) becomes red. See screenshots for “off” and “on” view:

- PrettyJSON is **off**:

<img width="564" alt="off" src="https://user-images.githubusercontent.com/79277751/171707474-5474c73b-5e41-48b0-a22a-8d35ab38f18f.png">

- PrettyJSON is **on**:

<img width="559" alt="on" src="https://user-images.githubusercontent.com/79277751/171707503-b2b85acb-9fb7-4d11-83fd-321184071cdb.png">

**Comment by ayman** [comment]
Well thats weird. It doesnt do any injection afaik but might be a CSS collision somewhere.  There was a recent PR #8 around CSS stuff...I'll keep an eye and maybe update my namespaces to be more uniquely hashed.
