### ISSUE TITLE
App approved?

### ISSUE THREAD

**Issue by jonnyijapan** [ayman/PrettyJSON#4]
Is the app published yet?

**Comment by keithws** [comment]
I searched the app store but I do not see this app. I would love too!

**Comment by geerlingguy** [comment]
Right now I'm trying out Asini JSON (which works okay, though I couldn't find out much about who publishes it and whether the source is available anywhere), but I'd also love to get this app once approved.

**Comment by skitapa** [comment]
I checked the ones on the App Store but as the plugin has access to all web history and all your passwords typed into the browser I would not dream of installing a closed source beautifier. Would be nice to see a safe one on the store.

**Comment by keithws** [comment]
I agree with @skitapa. I wanted something I could use now, so I created an open-source Bookmarklet, [JSONBeautifier](https://github.com/keithws/JSONBeautifier).

**Comment by ayman** [comment]
Sorry! I lost sight of this...but it's in store and a proper signed extension: https://apps.apple.com/us/app/id1445328303  Code folding coming next. Feel free to send in PRs too. Easier to push now after the month it took to get it into the store. 😄
