### ISSUE TITLE
CSS also affects other web sites

### ISSUE THREAD

**Issue by vandelay** [ayman/PrettyJSON#7]
First, thanks for this extension.

We use a commercial web site which also uses CSS class `number` and they were appearing in `darkorange` on my machine as the CSS in this extension overrides the styling on the site.

**Comment by grahamb** [comment]
Also seeing this when using `semantic-ui`; I have an icon with class `.key`. 

Your CSS should be namespaced to prevent collisions like this, and ideally (don't know if this is possible with Safari's extension APIs) only active when viewing actual JSON.

![Screen Shot 2021-12-15 at 11 47 07](https://user-images.githubusercontent.com/146111/146255089-cba9451c-91ff-48dd-ad1c-239a3da48af3.png)

**Comment by ayman** [comment]
Woo thanks! I'll get a new build posted soon.
